### ISSUE TITLE
Зарегистрировать все аккаунты

### ISSUE THREAD

**Issue by roll** [arunalabru/arunalab.ru#15]
на arunalabru@arunalab.ru

**Comment by roll** [comment]
готово
![1](https://cloud.githubusercontent.com/assets/557395/7427840/7b734fc0-efe4-11e4-890f-1c51e4b67644.png)

**Comment by L1SS** [comment]
Круто, а как мне это проверить, я в этом еще не разбираюсь (((

**Comment by roll** [comment]
Нужно установить хром и там войти в аккаунт arunalabru@arunalab.ru. В смысле в самом браузере в аккаунт для синхронизации и т.п. Пароль я скину в личный чат.

**Comment by L1SS** [comment]
Проверил! Закрываю
